
server:
  port: 8777

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/payment_micro
    username: root
    password: toor
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
   # database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT
    
  config:
    import:
    - configserver:http://localhost:9292   